export interface Article {
  slug: string;
  title: string;
  description: string;
  category: string;
  categoryEmoji: string;
  readTime: number;
  isNew?: boolean;
  toolkitLink?: string;
  toolkitName?: string;
  content?: string;
}

export const CATEGORIES = [
  { id: "all", label: "All Articles", emoji: "" },
  { id: "budgeting", label: "Budgeting", emoji: "💰" },
  { id: "debt", label: "Debt", emoji: "📉" },
  { id: "savings", label: "Savings", emoji: "🏦" },
  { id: "spending", label: "Spending", emoji: "🛒" },
  { id: "financial-health", label: "Financial Health", emoji: "💪" },
  { id: "financial-security", label: "Financial Security", emoji: "🔒" },
  { id: "account-sync", label: "Account Sync", emoji: "🔗" },
];

export const ARTICLES: Article[] = [
  // Budgeting
  {
    slug: "50-30-20-rule",
    title: "The 50/30/20 Budget Rule",
    description: "Learn how to allocate 50% needs, 30% wants, 20% savings",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 6,
  },
  {
    slug: "zero-based-budgeting",
    title: "Zero-Based Budgeting",
    description: "Learn how zero-based budgeting works and why it's the most powerful method for taking control of your money.",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "envelope-method",
    title: "The Envelope Method",
    description: "Use cash envelopes to control spending in every category",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 5,
  },
  {
    slug: "essential-budget-categories",
    title: "Essential Budget Categories",
    description: "The complete list of budget categories you need to track",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 6,
  },
  {
    slug: "track-expenses",
    title: "How to Track Expenses Effectively",
    description: "Simple systems to track every dollar without spreadsheet overwhelm",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 6,
  },
  {
    slug: "budgeting-mistakes",
    title: "Common Budgeting Mistakes to Avoid",
    description: "The 10 most common budgeting mistakes and how to fix them",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 7,
  },
  {
    slug: "paycheck-breakdown-toolkit",
    title: "Paycheck Breakdown Toolkit",
    description: "Allocate every dollar of every paycheck before it disappears",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Paycheck Breakdown Toolkit",
  },
  {
    slug: "2-paycheck-budget-system",
    title: "2-Paycheck Budget System",
    description: "Allocate each paycheck to specific bills and expenses",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "2-Paycheck Budget System",
  },
  {
    slug: "irregular-income-budget",
    title: "Irregular Income Budget Kit",
    description: "Budget confidently with variable or freelance income",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 8,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Irregular Income Budget Kit",
  },
  {
    slug: "annual-bills-planner",
    title: "Annual Bills Planner",
    description: "Plan and fund every annual expense before it arrives",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 6,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Annual Bills Planner",
  },
  {
    slug: "ai-powered-budgeting",
    title: "AI-Powered Budgeting",
    description: "How AI tools are transforming personal budgeting",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 5,
  },
  {
    slug: "budget-on-autopilot",
    title: "Budget on Autopilot",
    description: "Set up automatic transfers and rules to budget without thinking",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 5,
  },
  {
    slug: "emergency-budget-adjustments",
    title: "Emergency Budget Adjustments",
    description: "How to quickly adjust your budget when income drops or expenses spike",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 5,
  },
  {
    slug: "budgeting-for-beginners",
    title: "Budgeting for Beginners",
    description: "Everything you need to know to create your first budget and actually stick to it.",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 10,
    isNew: true,
  },
  {
    slug: "stop-living-paycheck-to-paycheck",
    title: "How to Stop Living Paycheck to Paycheck",
    description: "Break the paycheck-to-paycheck cycle with a practical, step-by-step plan that actually works.",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 9,
    isNew: true,
  },
  {
    slug: "zero-based-budgeting-advanced",
    title: "Zero-Based Budgeting",
    description: "Learn how zero-based budgeting works and why it's the most powerful method for taking control of your money.",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 7,
    isNew: true,
  },

  // Debt
  {
    slug: "debt-snowball",
    title: "Debt Snowball Method",
    description: "Pay off smallest debts first for psychological wins",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 6,
  },
  {
    slug: "debt-avalanche",
    title: "Debt Avalanche Method",
    description: "Pay off highest-interest debts first to save the most money",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 6,
  },
  {
    slug: "good-debt-vs-bad-debt",
    title: "Good Debt vs Bad Debt",
    description: "Understanding which debt builds wealth and which destroys it",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 5,
  },
  {
    slug: "understanding-credit-score",
    title: "Understanding Your Credit Score",
    description: "What affects your credit score and how to improve it fast",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
  },
  {
    slug: "debt-consolidation",
    title: "Debt Consolidation Options",
    description: "Compare balance transfers, personal loans, and other consolidation strategies",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
  },
  {
    slug: "student-loan-debt",
    title: "Managing Student Loan Debt",
    description: "Repayment plans, forgiveness programs, and refinancing options",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 8,
  },
  {
    slug: "credit-card-debt",
    title: "Escaping Credit Card Debt",
    description: "A step-by-step plan to eliminate credit card debt for good",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
  },
  {
    slug: "emergency-debt-management",
    title: "Emergency Debt Management",
    description: "What to do when you can't make minimum payments",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 6,
  },
  {
    slug: "bill-catch-up-plan",
    title: "Bill Catch-Up Plan",
    description: "Get current on late bills with a systematic catch-up plan",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Bill Catch-Up Plan",
  },
  {
    slug: "debt-snowball-vs-avalanche",
    title: "Debt Snowball vs. Avalanche Method",
    description: "Compare the two most popular debt payoff strategies and find out which one will save you more money.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "how-to-pay-off-debt",
    title: "How to Pay Off Debt",
    description: "A comprehensive, step-by-step plan to pay off all your debt — credit cards, student loans, car loans, and more.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 10,
    isNew: true,
  },

  // Savings
  {
    slug: "emergency-fund",
    title: "Building Your Emergency Fund",
    description: "Why you need 3-6 months of expenses saved",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 6,
  },
  {
    slug: "52-week-savings-challenge",
    title: "52-Week Savings Challenge",
    description: "Save $1,378 in one year with this simple weekly challenge",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 5,
  },
  {
    slug: "high-yield-savings",
    title: "High-Yield Savings Accounts Explained",
    description: "How to earn 10x more interest on your savings",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 6,
  },
  {
    slug: "automating-savings",
    title: "Automating Your Savings",
    description: "Set up automatic transfers to save without thinking about it",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 5,
  },
  {
    slug: "smart-savings-goals",
    title: "Setting SMART Savings Goals",
    description: "How to set specific, measurable savings goals you'll actually hit",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 6,
  },
  {
    slug: "sinking-funds",
    title: "Sinking Funds Kit",
    description: "Save for irregular expenses without stress",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Sinking Funds Kit",
  },
  {
    slug: "how-to-build-emergency-fund",
    title: "How to Build an Emergency Fund",
    description: "A step-by-step guide to building a 3-6 month emergency fund, even when money is tight.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "how-to-save-money-fast",
    title: "How to Save Money Fast",
    description: "Practical, no-fluff strategies to save more money quickly — whether you need $500 or $5,000.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "how-to-invest",
    title: "How to Invest Money for Beginners",
    description: "A plain-English guide to investing for beginners — from your first $100 to building long-term wealth.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 10,
    isNew: true,
  },

  // Spending
  {
    slug: "compound-interest",
    title: "The Power of Compound Interest",
    description: "How compound interest works and why starting early matters",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 6,
  },
  {
    slug: "lifestyle-inflation",
    title: "Avoiding Lifestyle Inflation",
    description: "Why earning more doesn't always mean saving more — and how to fix it",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 6,
  },
  {
    slug: "money-habits",
    title: "Building Positive Money Habits",
    description: "The daily and weekly habits that separate financially secure people",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 6,
  },
  {
    slug: "food-budget-reset",
    title: "Food Budget Reset Kit",
    description: "Reduce food spending by 20–30% without sacrifice",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Food Budget Reset Kit",
  },
  {
    slug: "spending-cuts",
    title: "Spending Cuts That Don't Hurt",
    description: "Cut spending without sacrificing quality of life",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 7,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Spending Cuts That Don't Hurt",
  },
  {
    slug: "no-overdraft-system",
    title: "No-Overdraft System",
    description: "Eliminate overdraft fees permanently",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 6,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "No-Overdraft System",
  },

  // Financial Health
  {
    slug: "net-worth",
    title: "Calculating Your Net Worth",
    description: "Assets minus liabilities = your financial health",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 5,
  },
  {
    slug: "financial-goals",
    title: "Setting Financial Goals",
    description: "How to set and achieve meaningful financial goals",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 6,
  },
  {
    slug: "insurance-coverage",
    title: "Essential Insurance Coverage",
    description: "The insurance policies everyone needs and how much coverage to get",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
  },
  {
    slug: "tax-planning",
    title: "Basic Tax Planning Strategies",
    description: "Legal ways to reduce your tax bill every year",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
  },
  {
    slug: "estate-planning",
    title: "Estate Planning Essentials",
    description: "Wills, trusts, and beneficiaries — what you need and when",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
  },
  {
    slug: "retirement-savings",
    title: "How Much to Save for Retirement",
    description: "Calculate your retirement number and build a plan to get there",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 8,
  },
  {
    slug: "financial-literacy",
    title: "Why Financial Literacy Matters",
    description: "The real cost of not understanding money — and how to fix it",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 5,
  },
  {
    slug: "financial-independence",
    title: "Path to Financial Independence",
    description: "The FIRE movement explained and how to reach financial freedom",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 8,
  },
  {
    slug: "money-stress",
    title: "Managing Money-Related Stress",
    description: "The psychology of money anxiety and practical ways to reduce it",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 6,
  },
  {
    slug: "teaching-kids-money",
    title: "Teaching Kids About Money",
    description: "Age-appropriate ways to raise financially smart children",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
  },
  {
    slug: "budget-toolkit-bundle",
    title: "Complete Budget Toolkit Bundle",
    description: "One toolkit. Ten budgeting systems. The complete money reset.",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 8,
    isNew: true,
    toolkitLink: "https://stan.store/sheklaai",
    toolkitName: "Budget Toolkit Bundle (All 10)",
  },
  {
    slug: "what-is-good-credit-score",
    title: "What Is a Good Credit Score?",
    description: "Understand credit score ranges, what affects your score, and proven strategies to improve it fast.",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "personal-finance-tips",
    title: "Personal Finance Tips for Every Stage of Life",
    description: "Timeless personal finance principles that apply whether you're 22 or 52 — and just getting started.",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 9,
    isNew: true,
  },
  {
    slug: "cash-flow-clarity",
    title: "Cash Flow Clarity",
    description: "Understanding and optimizing your monthly cash flow",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 6,
  },
  {
    slug: "investment-intelligence",
    title: "Investment Intelligence",
    description: "Smart investing principles for long-term wealth building",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 7,
  },

  // Financial Security
  {
    slug: "two-factor-authentication",
    title: "Two-Factor Authentication",
    description: "Why 2FA is essential for protecting your financial accounts",
    category: "financial-security",
    categoryEmoji: "🔒",
    readTime: 5,
  },
  {
    slug: "phishing-scams",
    title: "Recognizing Phishing Scams",
    description: "How to spot and avoid financial phishing attacks",
    category: "financial-security",
    categoryEmoji: "🔒",
    readTime: 6,
  },
  {
    slug: "password-security",
    title: "Password Security",
    description: "Best practices for securing your financial accounts with strong passwords",
    category: "financial-security",
    categoryEmoji: "🔒",
    readTime: 6,
  },
  {
    slug: "data-protection",
    title: "Data Protection & Encryption",
    description: "How your financial data is protected and what you can do to add more security",
    category: "financial-security",
    categoryEmoji: "🔒",
    readTime: 6,
  },
  {
    slug: "identity-protection",
    title: "Identity Protection",
    description: "How to protect yourself from identity theft and what to do if it happens",
    category: "financial-security",
    categoryEmoji: "🔒",
    readTime: 7,
  },

  // Account Sync
  {
    slug: "open-banking",
    title: "Understanding Open Banking",
    description: "What open banking is and how it powers financial apps like Shekla",
    category: "account-sync",
    categoryEmoji: "🔗",
    readTime: 7,
  },
  {
    slug: "data-privacy",
    title: "Managing Data Privacy",
    description: "How to control what financial data apps can access",
    category: "account-sync",
    categoryEmoji: "🔗",
    readTime: 7,
  },
  {
    slug: "bank-connection-guide",
    title: "Secure Bank Connection Guide",
    description: "Step-by-step guide to securely connecting your bank accounts",
    category: "account-sync",
    categoryEmoji: "🔗",
    readTime: 7,
  },
  {
    slug: "real-time-sync",
    title: "Real-Time Financial Sync",
    description: "How real-time transaction syncing works and why it matters",
    category: "account-sync",
    categoryEmoji: "🔗",
    readTime: 7,
  },
  {
    slug: "sync-troubleshooting",
    title: "Sync Troubleshooting Guide",
    description: "How to fix common bank connection and sync issues",
    category: "account-sync",
    categoryEmoji: "🔗",
    readTime: 7,
  },

  // New SEO Articles - June 2026
  {
    slug: "what-is-a-credit-union",
    title: "What Is a Credit Union? Banks vs. Credit Unions Explained",
    description: "Discover the differences between credit unions and traditional banks, the pros and cons of each, and how to choose the right place for your money.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "how-do-personal-loans-work",
    title: "How Do Personal Loans Work? A Complete Guide",
    description: "Learn what a personal loan is, how the application process works, and when it makes sense to use one for debt consolidation or major expenses.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "what-is-a-high-yield-savings-account",
    title: "What Is a High-Yield Savings Account (HYSA)?",
    description: "Learn how high-yield savings accounts work, why they pay significantly more interest than traditional banks, and how to choose the right one.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 6,
    isNew: true,
  },

  // New SEO Articles - June 2026 (Week 2)
  {
    slug: "what-is-a-401k",
    title: "What Is a 401(k)? 401(k) vs. IRA Explained for Beginners",
    description: "Learn what a 401(k) is, how it compares to an IRA, and the best strategy for using both to build a secure retirement.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "how-to-save-for-a-house",
    title: "How to Save for a House: A Step-by-Step Guide",
    description: "A practical, step-by-step plan for first-time buyers to save for a down payment — from setting your target to automating your savings.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 9,
    isNew: true,
  },
  {
    slug: "how-to-check-credit-score",
    title: "What Is a Credit Score and How to Check It Safely",
    description: "Understand exactly what makes up your credit score, what the ranges mean, and how to check it for free without hurting it.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
    isNew: true,
  },

  // New SEO Articles - June 2026 (Week 3)
  {
    slug: "how-to-refinance-a-mortgage",
    title: "How to Refinance a Mortgage: A Beginner's Guide",
    description: "Learn how mortgage refinancing works, when it makes financial sense to do it, and a step-by-step guide to the process.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "what-are-etfs",
    title: "What Are ETFs? A Beginner's Guide to Exchange-Traded Funds",
    description: "Discover what ETFs are, how they differ from mutual funds, and why they are one of the best ways for beginners to start investing.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "how-to-negotiate-salary",
    title: "How to Negotiate a Salary Raise: 7 Proven Steps",
    description: "A practical guide to asking for a raise, complete with research strategies, timing tips, and scripts to help you get the pay you deserve.",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 9,
    isNew: true,
  },

  // New SEO Articles - June 2026 (Week 4)
  {
    slug: "money-market-vs-savings-account",
    title: "Money Market Account vs. Savings Account: Which Is Right for You?",
    description: "Understand the key differences between money market accounts and traditional savings accounts to maximize your interest and access to your cash.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "how-to-make-a-budget-step-by-step",
    title: "How to Make a Budget for Beginners: A Step-by-Step Guide",
    description: "Learn how to create a simple, effective monthly budget from scratch in just 5 easy steps. Take control of your money today.",
    category: "budgeting",
    categoryEmoji: "💰",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "how-to-build-wealth-20s-30s",
    title: "How to Build Wealth in Your 20s and 30s: A Practical Guide",
    description: "Discover the proven, no-nonsense strategies to start building long-term wealth early in your career, leveraging time and compound interest.",
    category: "financial-health",
    categoryEmoji: "💪",
    readTime: 9,
    isNew: true,
  },

  // New SEO Articles - May 2026
  {
    slug: "how-to-open-roth-ira",
    title: "How to Open a Roth IRA: A Beginner's Guide",
    description: "Learn what a Roth IRA is, why you need one, and a step-by-step guide to opening your account today.",
    category: "savings",
    categoryEmoji: "🏦",
    readTime: 8,
    isNew: true,
  },
  {
    slug: "what-is-a-mortgage",
    title: "What Is a Mortgage and How Does It Work?",
    description: "A simple, jargon-free explanation of mortgages, interest rates, and the home buying process.",
    category: "debt",
    categoryEmoji: "📉",
    readTime: 7,
    isNew: true,
  },
  {
    slug: "best-side-hustles",
    title: "Best Side Hustles to Make Extra Money",
    description: "Discover proven ways to earn extra income online and offline to reach your financial goals faster.",
    category: "spending",
    categoryEmoji: "🛒",
    readTime: 9,
    isNew: true,
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function getArticlesByCategory(category: string): Article[] {
  if (category === "all") return ARTICLES;
  return ARTICLES.filter((a) => a.category === category);
}

export function getFeaturedArticles(): Article[] {
  return [
    ARTICLES.find((a) => a.slug === "50-30-20-rule")!,
    ARTICLES.find((a) => a.slug === "debt-snowball")!,
    ARTICLES.find((a) => a.slug === "emergency-fund")!,
    ARTICLES.find((a) => a.slug === "net-worth")!,
    ARTICLES.find((a) => a.slug === "budgeting-for-beginners")!,
    ARTICLES.find((a) => a.slug === "how-to-pay-off-debt")!,
    ARTICLES.find((a) => a.slug === "how-to-invest")!,
  ].filter(Boolean);
}
